### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by Eli-Black-Work** [newoga/simple-assign#1]
Hello,

Could you please add a LICENSE file to this project?

**Comment by newoga** [comment]
@Bosch-Eli-Black I just added an MIT license to the repo. Let me know if you need me to cut a release so that the license is part of the dependency on `npm`.

Although I am curious, what is your use case for this project? There may be better alternatives at this point because this project was created for a very specific reason which is no longer relevant.

**Comment by Eli-Black-Work** [comment]
Thanks, @newoga!

At least for our needs, I don't think we need a new release of the `npm` package.

It looks like the old Material UI `npm` package (https://www.npmjs.com/package/material-ui) has a dependency on simple-assign, so our project also has a subdependency on it.

**Comment by newoga** [comment]
@Bosch-Eli-Black No problem, makes sense. Material-UI was the very specific reason this was created and we have moved away from it in newer releases.

**Comment by Eli-Black-Work** [comment]
@newoga Thanks again :)
